application: gaek
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: .*
  script: main.app

- url: /assets
  static_dir: assets


libraries:
- name: "webapp2"
  version: "2.3"

- name: "jinja2"
  version: "2.6"